spring:
  profiles : test
---
spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: ${DB_URL}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        connectionTimeout: {DB_CONNECTION_TIMEOUT}